include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.generated.dart
    - lib/generated/

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_parameters: true
    avoid_final_parameters: false
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true